#!/bin/bash

# First build with all combinations of features to check for doc
# issues.  Then finally build as docs.rs sees it to visually check the
# annotations on some types.

./run-feature-combinations | while read features; do
    echo "=== Features: $features"
    cargo doc --no-default-features --features "$features" || exit 1
done

echo "=== docs.rs build with feature labels" &&
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
